(() => {
  'use strict';
  const $ = (s, root = document) => root.querySelector(s);
  const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const paths = {
    grid:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',
    config:'<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="9" cy="6" r="2"/><circle cx="15" cy="12" r="2"/><circle cx="9" cy="18" r="2"/>',
    model:'<rect x="5" y="5" width="14" height="14" rx="3"/><path d="M9 1v4m6-4v4M9 19v4m6-4v4M1 9h4m-4 6h4M19 9h4m-4 6h4"/><rect x="9" y="9" width="6" height="6" rx="1"/>',
    user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',
    plugin:'<path d="M9 3H4v6h2a2 2 0 1 1 0 4H4v7h6v-2a2 2 0 1 1 4 0v2h6v-7h-2a2 2 0 1 1 0-4h2V3h-6v2a2 2 0 1 1-4 0V3Z"/>',
    data:'<path d="M4 20V4m0 16h16M8 16v-5m5 5V6m5 10v-8"/>',
    settings:'<path d="m9 3-1 3-3 1-2 3 2 2-1 3 2 3 3-1 3 2 3-2 3 1 2-3-1-3 2-2-2-3-3-1-1-3Z"/><circle cx="12" cy="12" r="3"/>',
    menu:'<path d="M4 6h16M4 12h16M4 18h16"/>', refresh:'<path d="M20 7v5h-5M4 17v-5h5M6 6a8 8 0 0 1 14 6M4 12a8 8 0 0 0 14 6"/>',
    sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>', moon:'<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>',
    search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>', plus:'<path d="M12 5v14M5 12h14"/>', edit:'<path d="m16 3 5 5-12 12-6 1 1-6Zm-3 3 5 5"/>',
    save:'<path d="M3 3h15l3 3v15H3ZM7 3v6h10V3M7 21v-8h10v8"/>', close:'<path d="m6 6 12 12M6 18 18 6"/>', arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>', check:'<path d="m5 12 4 4L19 6"/>', log:'<path d="m4 6 5 6-5 6m9 0h7"/>'
  };
  const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name] || paths.config}</svg>`;
  $$('[data-icon]').forEach(el => { el.innerHTML = icon(el.dataset.icon); });
  const nav = [['工作台', [['dashboard','仪表盘','grid','dashboard']]], ['机器人管理', [['config','配置文件','config','config/ai/model'], ['models','模型服务','model','models'], ['personas','人设管理','user','personas'], ['plugins','插件管理','plugin','plugins']]], ['运行监控', [['data','数据与日志','data','data/runs']]]];
  $('#sidebar-nav').innerHTML = nav.map(([group, entries]) => `<span class="nav-caption">${group}</span>${entries.map(([page, name, glyph, route]) => `<a href="#${route}" data-page="${page}" aria-label="${name}" title="${name}"><span data-icon="${glyph}">${icon(glyph)}</span><span>${name}</span>${page === 'plugins' ? '<small class="nav-count"></small>' : ''}</a>`).join('')}`).join('');
  const names = { dashboard:'仪表盘', config:'配置文件', models:'模型服务', personas:'人设管理', plugins:'插件管理', data:'数据与日志', settings:'设置' };
  const statusNames = { queued:'排队', running:'运行中', completed:'已完成', failed:'失败', cancelled:'已取消', interrupted:'已中断', sent:'已送达', pending:'待投递', unknown:'未知', none:'—' };
  const tools = [['calculator_evaluate','计算器'], ['clock_now','当前时间'], ['knowledge_search','知识检索'], ['memory_search','用户记忆'], ['plugin_list','已生成插件'], ['plugin_create','编写插件'], ['plugin_run','运行插件']];
  const pluginInfo = {
    utilities:{name:'实用命令',id:'utility',icon:'config',color:'blue',description:'掷骰子、随机选择和身份查看，让日常群聊更方便。',commands:'/roll · /choose · /whoami · /plugins'},
    memory:{name:'持久记忆',id:'memory',icon:'user',color:'purple',description:'保存用户主动提供的记忆，按群、私聊和用户隔离。',commands:'/remember · /memories · /forget'},
    autoReply:{name:'关键词回复',id:'auto-reply',icon:'log',color:'green',description:'群内无需 @，匹配关键词直接回复，支持群范围与冷却时间。',commands:'完全匹配 / 包含关键词'},
    humanize:{name:'拟人化输出',id:'humanize',icon:'edit',color:'orange',description:'去掉回复末尾的终止标点，让短句更像日常聊天。保护代码、链接、引用和省略号。',commands:'Agent 与普通回复 · 发送前处理'}
  };
  const pluginCount=Object.keys(pluginInfo).length;
  $('.nav-count').textContent=String(pluginCount);
  $('#plugin-count').textContent=`${pluginCount} 个内置插件`;
  let csrf='', saved=null, draft=null, revision='', runs=[], logs=[], timer, toastTimer, dirty=false, saving=false, refreshing=false, applying=false, editorApply=null;
  const fieldErrors=new Map();
  const dialog=$('#editor-dialog');
  const systemTheme=matchMedia('(prefers-color-scheme: dark)');
  const prefRead=(key,fallback)=>{try{return localStorage.getItem(key)||fallback;}catch{return fallback;}};
  const prefWrite=(key,value)=>{try{localStorage.setItem(key,value);}catch{/* Storage may be unavailable. */}};
  let theme=prefRead('icy-theme','light');
  function applyTheme(){const dark=theme==='dark'||(theme==='system'&&systemTheme.matches);document.documentElement.dataset.theme=dark?'dark':'light';$('#theme-toggle').innerHTML=icon(dark?'sun':'moon');$('#theme-setting').value=theme;}
  function compact(value){document.documentElement.classList.toggle('compact',value);$('#compact-sidebar').checked=value;prefWrite('icy-sidebar',String(value));}
  applyTheme();compact(prefRead('icy-sidebar','false')==='true');systemTheme.addEventListener('change',applyTheme);
  $('#theme-toggle').onclick=()=>{theme=document.documentElement.dataset.theme==='dark'?'light':'dark';prefWrite('icy-theme',theme);applyTheme();};
  $('#theme-setting').onchange=e=>{theme=e.target.value;prefWrite('icy-theme',theme);applyTheme();};
  $('#compact-sidebar').onchange=e=>compact(e.target.checked);
  function closeDrawer(){document.documentElement.classList.remove('drawer-open');$('#drawer-shade').hidden=true;}
  $('#toggle-sidebar').onclick=()=>{if(matchMedia('(max-width: 900px)').matches){const open=document.documentElement.classList.toggle('drawer-open');$('#drawer-shade').hidden=!open;}else compact(!document.documentElement.classList.contains('compact'));};
  $('#drawer-shade').onclick=closeDrawer;
  $('#sidebar').addEventListener('click',e=>{if(e.target.closest('a'))closeDrawer();});
  for(const id of ['config-tabs','ai-tabs'])$('#'+id).addEventListener('click',e=>{if(e.target.closest('a')){$('#config-search').value='';filterConfig();}});
  function toast(message,error=false){const el=$('#toast');el.textContent=message;el.classList.toggle('error',error);el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.hidden=true;},error?7000:4500);}
  async function api(path,options={}){const response=await fetch(path,{credentials:'same-origin',cache:'no-store',...options});const data=await response.json().catch(()=>{throw new Error('服务返回了无效响应');});if(!response.ok){const error=new Error(data.error||'请求失败');error.status=response.status;throw error;}return data;}
  function authenticatedFailure(error){if(error.status===401){showLogin('登录已失效，请重新登录');return true;}return false;}
  function showLogin(message=''){$('#dashboard').hidden=true;$('#login-view').hidden=false;$('#login-message').textContent=message;clearInterval(timer);if(dialog.open)dialog.close();closeDrawer();}
  async function showDashboard(){const data=await api('/api/settings');saved=data.settings;draft=structuredClone(saved);revision=data.revision;fieldErrors.clear();renderSettings();$('#login-view').hidden=true;$('#dashboard').hidden=false;route();clearInterval(timer);timer=setInterval(()=>{if(!document.hidden)refresh();},15000);await refresh();}
  const time=v=>v?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
  const badge=v=>`<span class="badge ${esc(String(v||'').replace(/[^a-z]/g,''))}">${esc(statusNames[v]||v||'—')}</span>`;
  function tableRows(root,data){root.innerHTML=data.length?data.map(r=>`<tr><td>${esc(time(r.createdAt))}</td><td>${esc(r.session)}</td><td>${badge(r.status)}</td><td>${badge(r.delivery)}</td><td class="preview">${esc(r.inputPreview||r.resultPreview||'—')}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">暂无匹配任务</td></tr>';}
  function renderRuns(){const filtered=runs.filter(r=>!$('#status-filter').value||r.status===$('#status-filter').value);tableRows($('#recent-runs'),runs.slice(0,5));tableRows($('#runs-body'),filtered);$('#run-count').textContent=`· 最近 ${runs.length} 条`;}
  function renderLogs(){const term=$('#log-search').value.toLowerCase(),selected=logs.filter(line=>line.toLowerCase().includes(term)),root=$('#logs'),atEnd=root.scrollHeight-root.scrollTop-root.clientHeight<60;root.innerHTML=selected.length?selected.map(line=>`<div class="log-line ${line.includes(' ERROR ')?'error':line.includes(' WARN ')?'warn':''}">${esc(line)}</div>`).join(''):'<p class="empty">暂无匹配日志</p>';if(atEnd)root.scrollTop=root.scrollHeight;}
  async function refresh(){
    if(refreshing)return;refreshing=true;$('#refresh').disabled=true;
    try{const [summary,taskData,logData]=await Promise.all([api('/api/summary'),api('/api/runs'),api('/api/logs')]);
      $('#bot-state').textContent=summary.botActive?'运行中':'已停止';$('#total-runs').textContent=summary.totalRuns.toLocaleString('zh-CN');$('#active-runs').textContent=String((summary.byStatus.queued||0)+(summary.byStatus.running||0));$('#completed-runs').textContent=String(summary.byStatus.completed||0);
      $('#last-updated').textContent='最近更新 '+new Date().toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai'});$('#connection-badge').className='badge '+(summary.botActive?'ok':'error');$('#connection-badge').textContent=summary.botActive?'运行中':'已停止';
      runs=taskData.runs;logs=logData.lines;renderRuns();renderLogs();$('#status-stats').innerHTML=['queued','running','completed','failed','cancelled','interrupted'].map(s=>`<div class="status-stat"><span>${statusNames[s]}</span><progress max="${Math.max(1,summary.totalRuns)}" value="${summary.byStatus[s]||0}" aria-label="${statusNames[s]}"></progress><strong>${summary.byStatus[s]||0}</strong></div>`).join('');
    }catch(error){if(!authenticatedFailure(error)){$('#connection-badge').className='badge error';$('#connection-badge').textContent='读取失败';$('#last-updated').textContent=error.message;}}finally{refreshing=false;$('#refresh').disabled=false;}
  }
  function parts(){const p=location.hash.slice(1).split('/');return Object.hasOwn(names,p[0])?p:['dashboard'];}
  function route(){const p=parts();$$('.page').forEach(el=>{el.hidden=el.id!==`page-${p[0]}`;});$$('[data-page]').forEach(el=>{const active=el.dataset.page===p[0];el.classList.toggle('active',active);if(active)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});$('#breadcrumb').textContent=names[p[0]];document.title=`${names[p[0]]} · ICY`;closeDrawer();if(p[0]==='config')filterConfig();if(p[0]==='data'){const tab=['runs','logs','stats'].includes(p[1])?p[1]:'runs';$$('[data-data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.dataTab===tab));['runs','logs','stats'].forEach(s=>{$(`#data-${s}`).hidden=s!==tab;});if(tab==='logs')renderLogs();}updateDirty();}
  window.addEventListener('hashchange',route);
  const lines=value=>value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);
  const mappingText=value=>Object.entries(value).map(([key,id])=>`${key} = ${id}`).join('\n');
  function parseMapping(value){const result=Object.create(null);for(const line of lines(value)){const at=line.indexOf('='),key=line.slice(0,at).trim(),id=line.slice(at+1).trim();if(at<1||!key||!id||Object.hasOwn(result,key))throw new Error('每行填写 OpenID = 人设 ID，OpenID 不能重复');result[key]=id;}return result;}
  const getPath=(obj,path)=>path.split('.').reduce((v,key)=>v[key],obj);
  function setPath(obj,path,value){const keys=path.split('.'),last=keys.pop();keys.reduce((v,key)=>v[key],obj)[last]=value;}
  const switchHtml=(id,label,checked,extra='')=>`<label class="switch"><input id="${id}" type="checkbox" aria-label="${esc(label)}" ${checked?'checked':''} ${extra}><span class="switch-track"></span></label>`;
  const options=(values,chosen)=>values.map(([value,name])=>`<option value="${esc(value)}" ${value===chosen?'selected':''}>${esc(name)}</option>`).join('');
  function configField(path,label,hint,control,group){return `<div class="setting-field" data-group="${group}" data-search="${esc(`${label} ${hint} ${path}`.toLowerCase())}"><div class="field-info"><label for="cfg-${path}">${label}</label><p class="hint">${hint}</p></div><div class="field-control">${control}</div></div>`;}
  function renderConfig(){
    const bound=path=>`id="cfg-${path}" data-path="${path}"`,select=(path,values)=>`<select ${bound(path)}>${options(values,getPath(draft,path))}</select>`,num=(path,min,max)=>`<input ${bound(path)} type="number" min="${min}" max="${max}" value="${getPath(draft,path)}" required>`,area=(path,value,kind,hint)=>`<textarea ${bound(path)} data-kind="${kind}" rows="4" spellcheck="false" placeholder="${esc(hint||'')}">${esc(value)}</textarea>`,bool=(path,label)=>switchHtml(`cfg-${path}`,label,getPath(draft,path),`data-path="${path}"`),field=configField;
    $('#config-fields').innerHTML=[
      field('agent.enabled','启用 Agent 对话','开启后，普通消息将进入 Agent 对话流程。',bool('agent.enabled','启用 Agent 对话'),'ai/model'),
      field('agent.modelAlias','默认模型','选择 Agent 使用的模型连接；连接详情在模型服务中编辑。',select('agent.modelAlias',draft.models.map(m=>[m.alias,`${m.alias} · ${m.model}`]))+'<a class="text-button" href="#models">管理模型服务 →</a>','ai/model'),
      field('persona.defaultId','默认人设','没有单独分配人设的会话使用此人设。',select('persona.defaultId',draft.persona.profiles.map(p=>[p.id,`${p.name} (${p.id})`]))+'<a class="text-button" href="#personas">管理人设 →</a>','ai/persona'),
      field('persona.groupAssignments','群人设分配','每行填写：群 OpenID = 人设 ID。留空时使用默认人设。',area('persona.groupAssignments',mappingText(draft.persona.groupAssignments),'mapping','group_openid = assistant'),'ai/persona'),
      field('persona.c2cAssignments','私聊人设分配','每行填写：用户 OpenID = 人设 ID。',area('persona.c2cAssignments',mappingText(draft.persona.c2cAssignments),'mapping','user_openid = assistant'),'ai/persona'),
      field('policy.enabledTools','可调用的工具','仅勾选的工具可由 Agent 调用。记忆检索还需要启用持久记忆插件。',`<div id="cfg-policy.enabledTools" class="checkbox-list" role="group" aria-label="可调用的工具">${tools.map(([id,label])=>`<label><input type="checkbox" data-tool="${id}" ${draft.policy.enabledTools.includes(id)?'checked':''}>${label}</label>`).join('')}</div>`,'ai/tools'),
      field('agent.outputLimit','输出 token 上限','限制每次模型回复的最大长度；不能超过模型连接的输出上限。',num('agent.outputLimit',1,2000),'ai/advanced'),
      field('agent.maxConcurrency','并发任务','最多同时运行的 Agent 任务数。',num('agent.maxConcurrency',1,64),'ai/advanced'),
      field('agent.maxQueue','排队任务上限','达到上限后拒绝新任务，避免积压。',num('agent.maxQueue',1,1000),'ai/advanced'),
      field('agent.maxModelCalls','每轮模型调用上限','限制一次任务中的 Agent 循环次数。',num('agent.maxModelCalls',1,20),'ai/advanced'),
      field('agent.maxToolCalls','每轮工具调用上限','限制一次任务中累计调用工具的次数。',num('agent.maxToolCalls',1,32),'ai/advanced'),
      field('policy.allowC2c','允许私聊','允许未封禁的用户在私聊中使用机器人。',bool('policy.allowC2c','允许私聊'),'platform'),
      field('policy.groupCommandsWithoutMention','群命令免 @','群内直接发送 /calc、/roll 等已注册命令即可触发，仍检查群白名单和用户权限。普通对话需 @机器人。',bool('policy.groupCommandsWithoutMention','群命令免 @'),'platform'),
      field('policy.allowedGroups','允许的群 OpenID','每行一个群 OpenID。仅列表中的群可以使用受权限控制的功能。',area('policy.allowedGroups',draft.policy.allowedGroups.join('\n'),'lines','每行一个群 OpenID'),'platform'),
      field('policy.blockedUsers','封禁用户 OpenID','每行一个用户 OpenID；封禁优先于群和私聊授权。',area('policy.blockedUsers',draft.policy.blockedUsers.join('\n'),'lines','每行一个用户 OpenID'),'platform')
    ].join('');filterConfig();
  }
  function filterConfig(){const p=parts(),category=p[1]==='platform'?'platform':'ai',sub=['model','persona','tools','advanced'].includes(p[2])?p[2]:'model',term=$('#config-search').value.trim().toLowerCase(),group=category==='platform'?'platform':`ai/${sub}`;let found=0;$$('[data-config]').forEach(el=>el.classList.toggle('active',el.dataset.config===category));$$('[data-sub]').forEach(el=>el.classList.toggle('active',el.dataset.sub===sub));$('#ai-tabs').hidden=category==='platform'||Boolean(term);$$('.setting-field').forEach(el=>{el.hidden=term?!el.dataset.search.includes(term):el.dataset.group!==group;if(!el.hidden)found++;});$('#config-empty').hidden=found>0;}
  function updateDirty(){dirty=Boolean(draft&&saved&&(JSON.stringify(draft)!==JSON.stringify(saved)||fieldErrors.size));$('#save-dock').hidden=!dirty||$('#dashboard').hidden;$('#draft-status').innerHTML='<span class="draft-dot"></span> '+(saving?'正在保存…':'配置已修改');$('#save-settings').disabled=saving;$('#discard').disabled=saving;if(parts()[0]==='dashboard'&&saved)renderSummary();}
  function renderSummary(){const setting=saved,persona=setting.persona.profiles.find(p=>p.id===setting.persona.defaultId);$('#config-summary').innerHTML=[['默认模型',setting.agent.modelAlias||'未配置'],['默认人设',persona?.name||'未配置'],['群聊授权',`${setting.policy.allowedGroups.length} 个群`],['启用插件',`${Object.values(setting.plugins).filter(p=>p.enabled).length} / ${pluginCount}`]].map(([label,value])=>`<div class="summary-row"><span>${label}</span><strong>${esc(value)}</strong></div>`).join('');}
  function renderModels(){$('#model-list').innerHTML=draft.models.length?draft.models.map((m,i)=>`<article class="card resource-card"><div class="resource-top"><span class="icon-tile blue">${icon('model')}</span><div class="resource-title"><h2>${esc(m.alias)}</h2><small>模型连接</small></div>${m.alias===draft.agent.modelAlias?'<span class="badge blue">默认</span>':''}</div><div class="resource-content"><p class="resource-description">${esc(m.model)}</p><div class="resource-detail"><span>服务地址</span><strong>${esc(m.baseUrl)}</strong></div><div class="resource-meta"><span class="badge neutral">${m.supportsTools?'支持工具调用':'纯文本对话'}</span></div></div><div class="card-bottom"><span class="muted">密钥由环境变量管理</span><button data-edit-model="${i}">${icon('edit')} 编辑</button></div></article>`).join(''):'<article class="card empty">尚未配置模型连接</article>';}
  function renderPersonas(){$('#persona-list').innerHTML=draft.persona.profiles.map((p,i)=>`<article class="card resource-card"><div class="resource-top"><span class="icon-tile purple">${icon('user')}</span><div class="resource-title"><h2>${esc(p.name)}</h2><small>${esc(p.id)}</small></div>${p.id===draft.persona.defaultId?'<span class="badge blue">默认</span>':''}</div><div class="resource-content"><p class="resource-description">${esc(p.description||'暂无简介')}</p><div class="prompt-preview">${esc(p.systemPrompt)}</div></div><div class="card-bottom"><button data-delete-persona="${i}" class="danger">删除</button><button data-edit-persona="${i}">${icon('edit')} 编辑人设</button></div></article>`).join('');}
  function renderPlugins(){
    $('#plugin-list').innerHTML=Object.entries(pluginInfo).map(([key,info])=>{const config=draft.plugins[key];return `<article class="card resource-card"><div class="resource-top"><span class="icon-tile ${info.color}">${icon(info.icon)}</span><div class="resource-title"><h2>${info.name}</h2><small>${info.id} · 内置插件</small></div>${switchHtml(`plugin-${key}`,`启用${info.name}`,config.enabled,`data-plugin="${key}"`)}</div><div class="resource-content"><p class="resource-description">${info.description}</p><div class="resource-meta"><span class="badge ${config.enabled?'ok':'neutral'}">${config.enabled?'已启用':'已停用'}</span>${key==='autoReply'?`<span class="badge neutral">${config.rules.length} 条规则</span>`:''}</div><p class="hint">${info.commands}</p></div><div class="card-bottom"><span class="muted">${key==='memory'?'用户主动保存 · 重启保留':'直接处理 · 无模型消耗'}</span><button data-edit-plugin="${key}" aria-label="配置${info.name}">${icon('settings')} 配置</button></div></article>`;}).join('');
    const commands=[['/roll 2d6','掷骰子','实用命令'],['/choose 火锅 | 烧烤','随机选择','实用命令'],['/whoami','查看当前用户与群 OpenID','实用命令'],['/plugins','查看启用的命令插件','实用命令'],['/remember 内容','主动保存一条记忆','持久记忆'],['/memories','查看自己的记忆','持久记忆'],['/forget ID / all','删除自己的记忆','持久记忆']];
    $('#command-list').innerHTML='<div class="table-wrap"><table><thead><tr><th>命令示例</th><th>功能</th><th>所属插件</th></tr></thead><tbody>'+commands.map(([c,d,p])=>`<tr><td>${esc(c)}</td><td>${d}</td><td>${p}</td></tr>`).join('')+'</tbody></table></div>';
  }
  function renderSettings(){renderConfig();renderModels();renderPersonas();renderPlugins();renderSummary();updateDirty();}
  $('#config-fields').addEventListener('input',e=>{const input=e.target;if(input.dataset.path){try{let value=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value;if(input.dataset.kind==='mapping')value=parseMapping(value);if(input.dataset.kind==='lines')value=lines(value);setPath(draft,input.dataset.path,value);input.setCustomValidity('');fieldErrors.delete(input.dataset.path);}catch(error){input.setCustomValidity(error.message);fieldErrors.set(input.dataset.path,error.message);}}if(input.dataset.tool){const enabled=new Set(draft.policy.enabledTools);if(input.checked)enabled.add(input.dataset.tool);else enabled.delete(input.dataset.tool);draft.policy.enabledTools=[...enabled];}if(input.dataset.path==='persona.defaultId')renderPersonas();if(input.dataset.path==='agent.modelAlias')renderModels();updateDirty();});
  function checkConfig(){const invalid=$$('#config-fields input, #config-fields textarea, #config-fields select').find(el=>!el.checkValidity());if(invalid){$('#config-search').value='';location.hash=`config/${invalid.closest('.setting-field').dataset.group}`;route();if(!dialog.open)invalid.reportValidity();throw new Error(invalid.validationMessage);}}
  const editorField=(key,label,value,attrs='',hint='',kind='input')=>`<div class="editor-field"><label for="edit-${key}">${label}</label>${kind==='textarea'?`<textarea id="edit-${key}" ${attrs}>${esc(value)}</textarea>`:`<input id="edit-${key}" value="${esc(value)}" ${attrs}>`}${hint?`<p class="hint">${hint}</p>`:''}</div>`;
  function openEditor(title,description,html,apply,label='应用此配置'){$('#editor-title').textContent=title;$('#editor-description').textContent=description;$('#editor-body').innerHTML=html;$('#editor-error').textContent='';$('#apply-editor').textContent=label;$('#apply-editor').hidden=!apply;$('#cancel-editor').textContent=apply?'取消':'关闭';editorApply=apply;if(!dialog.open)dialog.showModal();$('#editor-body').scrollTop=0;}
  function closeEditor(){if(!applying)dialog.close();}
  $('#close-editor').onclick=closeEditor;$('#cancel-editor').onclick=closeEditor;
  dialog.addEventListener('cancel',e=>{if(applying)e.preventDefault();});
  dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeEditor();}});
  async function validate(next){return(await api('/api/settings/validate',{method:'POST',headers:{'Content-Type':'application/json','X-ICY-CSRF':csrf},body:JSON.stringify({settings:next})})).settings;}
  async function stage(next,replace=false){if(!replace)checkConfig();const validated=await validate(next);draft=validated;fieldErrors.clear();renderSettings();}
  $('#editor-form').onsubmit=async e=>{e.preventDefault();if(!editorApply||applying)return;applying=true;$('#apply-editor').disabled=true;$('#close-editor').disabled=true;$('#cancel-editor').disabled=true;try{const message=await editorApply();dialog.close();if(message!==false)toast(typeof message==='string'?message:'已应用到草稿，点击“保存配置”生效');}catch(error){if(!authenticatedFailure(error))$('#editor-error').textContent=error.message;}finally{applying=false;$('#apply-editor').disabled=false;$('#close-editor').disabled=false;$('#cancel-editor').disabled=false;}};
  function editModel(index){const m=draft.models[index];openEditor('编辑模型服务','修改当前模型连接；密钥值不在页面显示。',editorField('alias','连接别名',m.alias,'readonly')+editorField('model','模型 ID',m.model,'required maxlength="160"')+editorField('baseUrl','服务地址',m.baseUrl,'type="url" required maxlength="1000"')+editorField('apiKeyEnv','密钥环境变量',m.apiKeyEnv,'readonly')+`<div class="editor-field"><label>工具调用</label>${switchHtml('edit-supportsTools','支持工具调用',m.supportsTools)}</div>`,async()=>{const next=structuredClone(draft);Object.assign(next.models[index],{model:$('#edit-model').value.trim(),baseUrl:$('#edit-baseUrl').value.trim(),supportsTools:$('#edit-supportsTools').checked});await stage(next);});}
  function editPersona(index){const p=index<0?{id:'',name:'',description:'',systemPrompt:''}:draft.persona.profiles[index];openEditor(index<0?'新建人设':'编辑人设','系统提示词将注入 Agent；群聊中不能通过命令切换。',`<div class="editor-grid">${editorField('id','人设 ID',p.id,`required maxlength="32" pattern="[a-z][a-z0-9_\\-]{0,31}" ${index<0?'':'readonly'}`,'小写字母开头，支持数字、下划线和短横线')}${editorField('name','显示名称',p.name,'required maxlength="80"')}</div>`+editorField('description','简介',p.description,'maxlength="160"')+editorField('systemPrompt','系统提示词',p.systemPrompt,'required maxlength="8000" rows="10"','描述机器人的角色、回答习惯与行为边界。','textarea'),async()=>{const next=structuredClone(draft),profile=Object.fromEntries(['id','name','description','systemPrompt'].map(k=>[k,$(`#edit-${k}`).value.trim()]));if(index<0)next.persona.profiles.push(profile);else next.persona.profiles[index]=profile;await stage(next);});}
  function deletePersona(index){const p=draft.persona.profiles[index],referenced=p.id===draft.persona.defaultId||Object.values(draft.persona.groupAssignments).includes(p.id)||Object.values(draft.persona.c2cAssignments).includes(p.id);if(referenced){toast('该人设正在使用，请先调整默认人设或会话分配',true);return;}openEditor('删除人设',`将从配置草稿中删除“${p.name}”。`,'<p class="muted">保存配置后生效。保存前可以通过“撤销修改”恢复。</p>',async()=>{const next=structuredClone(draft);next.persona.profiles.splice(index,1);await stage(next);},'删除人设');}
  function editPlugin(key){const config=draft.plugins[key];if(key==='autoReply'){showRules();return;}
    if(key==='humanize'){
      const fields=[['stripTerminalPunctuation','去除句末标点','去掉中英文句号、问号和感叹号；保留句中标点。'],['perLine','按每行处理','开启时处理每行的末尾；关闭时只处理整条回复的末尾。'],['includeCommands','包含直接命令回复','默认仅处理 Agent 和普通文本回复；开启后也处理斜杠命令的文本回复。']];
      openEditor('配置拟人化输出','发送前处理，不增加模型调用。',fields.map(([id,label,hint])=>`<div class="editor-field"><label>${label}</label>${switchHtml(`edit-${id}`,label,config[id])}<p class="hint">${hint}</p></div>`).join('')+'<div class="notice">示例：收到啦。 → 收到啦<br>省略号、代码块、行内代码、引用、表格、公式、JSON 和链接保守保留。</div>',async()=>{const next=structuredClone(draft);for(const [id]of fields)next.plugins.humanize[id]=$(`#edit-${id}`).checked;await stage(next);});return;
    }
    const html=key==='utilities'?editorField('maxDice','骰子数量上限',config.maxDice,'type="number" min="1" max="100" required'):editorField('maxEntries','每用户记忆条数上限',config.maxEntries,'type="number" min="1" max="100" required')+editorField('maxChars','每条记忆字数上限',config.maxChars,'type="number" min="1" max="1000" required')+`<div class="editor-field"><label>允许 Agent 检索用户记忆</label>${switchHtml('edit-memoryTool','允许 Agent 检索用户记忆',draft.policy.enabledTools.includes('memory_search'))}<p class="hint">检索工具只读，仅访问当前会话中该用户的记忆。</p></div>`;openEditor(`配置${pluginInfo[key].name}`,key==='memory'?'调低上限或停用插件不会删除已保存的记忆。':'直接命令不调用模型。',html,async()=>{const next=structuredClone(draft);if(key==='utilities')next.plugins[key].maxDice=Number($('#edit-maxDice').value);else{next.plugins[key].maxEntries=Number($('#edit-maxEntries').value);next.plugins[key].maxChars=Number($('#edit-maxChars').value);const enabled=new Set(next.policy.enabledTools);if($('#edit-memoryTool').checked)enabled.add('memory_search');else enabled.delete('memory_search');next.policy.enabledTools=[...enabled];}await stage(next);});}
  function showRules(){const rules=draft.plugins.autoReply.rules;openEditor('关键词回复配置','按顺序匹配第一条规则；可调整顺序、编辑或删除。',`<div class="rule-toolbar"><span class="muted">${rules.length} 条规则</span><button type="button" data-add-rule>${icon('plus')} 添加规则</button></div>`+(rules.length?rules.map((r,i)=>`<div class="rule-row"><div><strong>${esc(r.keyword)}</strong><small>${esc(r.id)} · ${r.match==='exact'?'完全匹配':'包含关键词'} · 冷却 ${r.cooldownSeconds} 秒</small></div><button type="button" data-move-rule="${i}" aria-label="上移规则 ${esc(r.id)}" ${i===0?'disabled':''}>↑</button><button type="button" data-edit-rule="${i}">编辑</button><button type="button" data-delete-rule="${i}" class="danger">删除</button></div>`).join(''):'<p class="empty">添加第一条关键词回复规则</p>'),null);}
  function editRule(index){const r=index<0?{id:'',keyword:'',match:'exact',reply:'',scopes:['group','c2c'],groupOpenids:[],cooldownSeconds:0}:draft.plugins.autoReply.rules[index];openEditor(index<0?'添加回复规则':'编辑回复规则','命中后直接回复；冷却期间保持静默。',`<div class="editor-grid">${editorField('id','规则 ID',r.id,'required maxlength="64" pattern="[a-z][a-z0-9_\\-]*"')}${editorField('keyword','关键词',r.keyword,'required maxlength="100"')}</div><div class="editor-grid"><div class="editor-field"><label for="edit-match">匹配方式</label><select id="edit-match">${options([['exact','完全匹配'],['contains','包含关键词']],r.match)}</select></div>${editorField('cooldownSeconds','冷却时间（秒）',r.cooldownSeconds,'type="number" min="0" max="86400" required')}</div>`+editorField('reply','回复文本',r.reply,'required maxlength="1500" rows="4"','','textarea')+`<div class="editor-field"><label>适用场景</label><div class="checkbox-list">${[['group','群聊'],['c2c','私聊']].map(([s,label])=>`<label><input type="checkbox" data-edit-scope="${s}" ${r.scopes.includes(s)?'checked':''}>${label}</label>`).join('')}</div></div>`+editorField('groups','指定群 OpenID',r.groupOpenids.join('\n'),'rows="3"','每行一个。留空表示全部已授权群。','textarea'),async()=>{const next=structuredClone(draft),rule={id:$('#edit-id').value.trim(),keyword:$('#edit-keyword').value.trim(),reply:$('#edit-reply').value.trim(),match:$('#edit-match').value,cooldownSeconds:Number($('#edit-cooldownSeconds').value),scopes:$$('[data-edit-scope]:checked').map(el=>el.dataset.editScope),groupOpenids:lines($('#edit-groups').value)};if(index<0)next.plugins.autoReply.rules.push(rule);else next.plugins.autoReply.rules[index]=rule;await stage(next);});}
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!draft)return;
    if(b.dataset.editModel!==undefined)editModel(Number(b.dataset.editModel));
    if(b.dataset.editPersona!==undefined)editPersona(Number(b.dataset.editPersona));
    if(b.dataset.deletePersona!==undefined)deletePersona(Number(b.dataset.deletePersona));
    if(b.dataset.editPlugin)editPlugin(b.dataset.editPlugin);
    if(b.hasAttribute('data-add-rule'))editRule(-1);
    if(b.dataset.editRule!==undefined)editRule(Number(b.dataset.editRule));
    if(b.dataset.deleteRule!==undefined){const i=Number(b.dataset.deleteRule);openEditor('删除回复规则',`删除“${draft.plugins.autoReply.rules[i].keyword}”规则`,'<p class="muted">保存配置后生效。</p>',async()=>{const next=structuredClone(draft);next.plugins.autoReply.rules.splice(i,1);await stage(next);},'删除规则');}
    if(b.dataset.moveRule!==undefined){const i=Number(b.dataset.moveRule);if(i>0){const rules=draft.plugins.autoReply.rules;[rules[i-1],rules[i]]=[rules[i],rules[i-1]];updateDirty();showRules();}}
    if(b.dataset.pluginTab){const commands=b.dataset.pluginTab==='commands';$('#command-list').hidden=!commands;$('#plugin-list').hidden=commands;$$('[data-plugin-tab]').forEach(el=>el.classList.toggle('active',el===b));}
  });
  $('#plugin-list').onchange=e=>{if(e.target.dataset.plugin){draft.plugins[e.target.dataset.plugin].enabled=e.target.checked;renderPlugins();updateDirty();}};
  $('#add-persona').onclick=()=>editPersona(-1);
  $('#edit-json').onclick=()=>openEditor('编辑 JSON 配置','应用时先校验并更新草稿，保存配置后才写入服务器。',editorField('json-config','配置 JSON',JSON.stringify(draft,null,2),'class="code-editor" rows="18" spellcheck="false" required','','textarea'),async()=>{let next;try{next=JSON.parse($('#edit-json-config').value);}catch{throw new Error('JSON 格式错误，请检查逗号、括号和引号');}await stage(next,true);});
  $('#config-search').oninput=filterConfig;$('#log-search').oninput=renderLogs;$('#status-filter').onchange=renderRuns;$('#refresh').onclick=refresh;
  $('#discard').onclick=()=>openEditor('撤销修改','将恢复为上次保存的配置。','<p class="muted">所有页面中未保存的配置修改都会被撤销。</p>',()=>{draft=structuredClone(saved);fieldErrors.clear();renderSettings();return '已撤销全部修改';},'撤销全部修改');
  $('#save-settings').onclick=async()=>{if(saving)return;try{checkConfig();const submitted=structuredClone(draft);saving=true;updateDirty();const result=await api('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json','X-ICY-CSRF':csrf},body:JSON.stringify({revision,settings:submitted})});revision=result.revision;saved=submitted;toast('配置已保存，机器人正在重新加载');updateDirty();setTimeout(refresh,2500);}catch(error){if(!authenticatedFailure(error))toast(error.message,true);}finally{saving=false;updateDirty();}};
  $('#login-form').onsubmit=async e=>{e.preventDefault();const b=$('#login-form button');b.disabled=true;$('#login-message').textContent='';try{const data=await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#password').value})});csrf=data.csrf;await showDashboard();$('#password').value='';}catch(error){$('#login-message').textContent=error.message;}finally{b.disabled=false;}};
  async function logout(){await api('/api/logout',{method:'POST'});saved=null;draft=null;dirty=false;showLogin();return false;}
  $('#logout').onclick=()=>{if(dirty)openEditor('退出登录','当前还有未保存的配置修改。','<p class="muted">退出后未保存的修改将丢失。</p>',logout,'放弃修改并退出');else logout().catch(error=>toast(error.message,true));};
  window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
  document.addEventListener('keydown',e=>{if(e.key==='/'&&parts()[0]==='config'&&!dialog.open&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();$('#config-search').focus();}if(e.key==='Escape')closeDrawer();});
  api('/api/auth').then(async data=>{if(data.authenticated){csrf=data.csrf;await showDashboard();}else showLogin();}).catch(error=>showLogin(error.message));
})();
